Gradle custom distribution
==========================

Creates custom gradle distribution. 

Downloads offficial distribution.
Creates custom one.
Created gradle-wrapper.properties.
Published to the maven repository.

Usage
=====
Configure gradle.properties to match your environment.

> gradle wrapperPropertiesForDistribution

Downloads the official distribution if not yet downloaded. Created custom distribution. Creates wrapper properties with SHA-256 checksum of custom distribution.

> gradle publish
	
Publishes just created distribution to the maven repository.

> gradle prepareTest

Copies the created gradle-wrapper.properties to the wrapper directory. 
If previously initiated with gradle wrapper created distribution can be checked with simle gradlew.

License
=======
    Copyright 2017 Ireneusz Spinalski

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.